/** ORDER */
export const ORDER_FINDALL="ORDER_FINDALL";
export const ORDER_FINDALL_SUCCESS="ORDER_FINDALL_SUCCESS";
export const ORDER_FINDALL_ERROR="ORDER_FINDALL_ERROR";
export const ORDER_CREATE="ORDER_CREATE";
export const ORDER_CREATE_SUCCESS="ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_ERROR="ORDER_CREATE_ERROR";
export const ORDER_DELETE="ORDER_DELETE";
export const ORDER_DELETE_SUCCESS="ORDER_DELETE_SUCCESS";
export const ORDER_DELETE_ERROR="ORDER_DELETE_ERROR";
export const ORDER_CHANGE_STATUS="ORDER_CHANGE_STATUS";
export const ORDER_CHANGE_STATUS_SUCCESS="ORDER_CHANGE_STATUS_SUCCESS";
export const ORDER_CHANGE_STATUS_ERROR="ORDER_CHANGE_STATUS_ERROR";
export const ORDER_ADD_TO_TRASH="ORDER_ADD_TO_TRASH";
export const ORDER_ADD_TO_TRASH_SUCCESS="ORDER_ADD_TO_TRASH_SUCCESS";
export const ORDER_ADD_TO_TRASH_ERROR="ORDER_ADD_TO_TRASH_ERROR";
export const ORDER_COUNT_BY_STATUS="ORDER_COUNT_BY_STATUS";
export const ORDER_COUNT_BY_STATUS_SUCCESS="ORDER_COUNT_BY_STATUS_SUCCESS";
export const ORDER_COUNT_BY_STATUS_ERROR="ORDER_COUNT_BY_STATUS_ERROR";
export const ORDER_UPDATE_QUICKVIEW="ORDER_UPDATE_QUICKVIEW";
export const ORDER_RESTORE = "ORDER_RESTORE";
export const ORDER_RESTORE_SUCCESS = "ORDER_RESTORE_SUCCESS";
export const ORDER_RESTORE_ERROR = "ORDER_RESTORE_ERROR";
export const ORDER_MERGE="ORDER_MERGE";
export const ORDER_MERGE_SUCCESS="ORDER_MERGE_SUCCESS";
export const ORDER_MERGE_ERROR="ORDER_MERGE_ERROR";
/**
 * Category actions
 * */
export const CATEGORY_REMOVE_ERROR = "CATEGORY_REMOVE_ERROR";
export const CATEGORY_REMOVE_SUCCESS = "CATEGORY_REMOVE_SUCCESS";
export const CATEGORY_FINDALL = "CATEGORY_FINDALL";
export const CATEGORY_FINDALL_SUCCESS = "CATEGORY_FINDALL_SUCCESS";
export const CATEGORY_FINDALL_ERROR = "CATEGORY_FINDALL_ERROR";
export const CATEGORY_CREATE = "CATEGORY_CREATE";
export const CATEGORY_CREATE_SUCCESS = "CATEGORY_CREATE_SUCCESS";
export const CATEGORY_CREATE_ERROR = "CATEGORY_CREATE_ERROR";
export const CATEGORY_DELETE = "CATEGORY_DELETE";
export const CATEGORY_DELETE_SUCCESS = "CATEGORY_DELETE_SUCCESS";
export const CATEGORY_DELETE_ERROR = "CATEGORY_DELETE_ERROR";
export const CATEGORY_UPDATE = "CATEGORY_UPDATE";
export const CATEGORY_UPDATE_SUCCESS = "CATEGORY_UPDATE_SUCCESS";
export const CATEGORY_UPDATE_ERROR = "CATEGORY_UPDATE_ERROR";
export const CATEGORY_SORTTREE = "CATEGORY_SORTTREE";
/**
 * Product actions
 * */
export const PRODUCT_FINDALL				= "PRODUCT_FINDALL";
export const PRODUCT_FINDALL_SUCCESS		= "PRODUCT_FINDALL_SUCCESS";
export const PRODUCT_FINDALL_ERROR			= "PRODUCT_FINDALL_ERROR";
export const PRODUCT_FINDPICKER				= "PRODUCT_FINDPICKER";
export const PRODUCT_SEARCHPICKER			= "PRODUCT_SEARCHPICKER";
export const PRODUCT_FINDPICKER_SUCCESS		= "PRODUCT_FINDPICKER_SUCCESS";
export const PRODUCT_FINDPICKER_ERROR		= "PRODUCT_FINDPICKER_ERROR";
export const PRODUCT_FINDBYID				= "PRODUCT_FINDBYID";
export const PRODUCT_FINDBYID_SUCCESS		= "PRODUCT_FINDBYID_SUCCESS";
export const PRODUCT_FINDBYID_ERROR			= "PRODUCT_FINDBYID_ERROR";
export const PRODUCT_CREATE_UPDATE			= "PRODUCT_CREATE_UPDATE";
export const PRODUCT_CREATE_UPDATE_SUCCESS	= "PRODUCT_CREATE_UPDATE_SUCCESS";
export const PRODUCT_CREATE_UPDATE_ERROR	= "PRODUCT_CREATE_UPDATE_ERROR";
export const PRODUCT_DELETE					= "PRODUCT_DELETE";
export const PRODUCT_DELETE_SUCCESS			= "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_ERROR			= "PRODUCT_DELETE_ERROR";
export const PRODUCT_REMOVE_MESSAGE			= "PRODUCT_REMOVE_MESSAGE";
export const PRODUCT_UPDATEKEYWORD			= "PRODUCT_UPDATEKEYWORD";
export const PRODUCT_UPDATEKEYWORD_SUCCESS		= "PRODUCT_UPDATEKEYWORD_SUCCESS";
export const PRODUCT_UPDATETOPFLAG_SUCCESS	= "PRODUCT_UPDATETOPFLAG_SUCCESS";
export const PRODUCT_UPDATETOPFLAG_ERROR	= "PRODUCT_UPDATETOPFLAG_ERROR";
export const PRODUCT_UPDATETOPFLAG			= "PRODUCT_UPDATETOPFLAG";

/**
 * User actions
 * */
export const USER_FINDALL = "USER_FINDALL";
export const USER_FINDALL_SUCCESS = "USER_FINDALL_SUCCESS";
export const USER_FINDALL_ERROR = "USER_FINDALL_ERROR";
export const USER_FINDONE = "USER_FINDONE";
export const USER_FINDONE_SUCCESS = "USER_FINDONE_SUCCESS";
export const USER_FINDONE_ERROR= "USER_FINDONE_ERROR";
export const USER_CREATE = "USER_CREATE";
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";
export const USER_CREATE_ERROR = "USER_CREATE_ERROR";
export const USER_DELETE = "USER_DELETE";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_ERROR = "USER_DELETE_ERROR";
export const USER_CHANGE_ROLE = "USER_CHANGE_ROLE";
export const USER_CHANGE_ROLE_SUCCESS = "USER_CHANGE_ROLE_SUCCESS";
export const USER_CHANGE_ROLE_ERROR = "USER_CHANGE_ROLE_ERROR";
export const ROLE_FINDALL = "ROLE_FINDALL";
export const ROLE_FINDALL_SUCCESS = "ROLE_FINDALL_SUCCESS";
export const ROLE_FINDALL_ERROR = "ROLE_FINDALL_ERROR";
export const ROLE_CREATE = "ROLE_CREATE";
export const ROLE_CREATE_SUCCESS = "ROLE_CREATE_SUCCESS";
export const ROLE_CREATE_ERROR = "ROLE_CREATE_ERROR";
export const ROLE_DELETE = "ROLE_DELETE";
export const ROLE_DELETE_SUCCESS = "ROLE_DELETE_SUCCESS";
export const ROLE_DELETE_ERROR = "ROLE_DELETE_ERROR";

/**
 * Image actions
 * */
export const IMAGE_TOGGLE_MODAL = "IMAGE_TOGGLE_MODAL";
export const IMAGE_FINDALL = "IMAGE_FINDALL";
export const IMAGE_FINDALL_SUCCESS = "IMAGE_FINDALL_SUCCESS";
export const IMAGE_FINDALL_ERROR = "IMAGE_FINDALL_ERROR";
export const IMAGE_UPLOAD = "IMAGE_UPLOAD";
export const IMAGE_UPLOAD_SUCCESS = "IMAGE_UPLOAD_SUCCESS";
export const IMAGE_UPLOAD_ERROR = "IMAGE_UPLOAD_ERROR";
export const IMAGE_ZIP_UPLOAD = "IMAGE_ZIP_UPLOAD";
export const IMAGE_ZIP_UPLOAD_SUCCESS = "IMAGE_ZIP_UPLOAD_SUCCESS";
export const IMAGE_ZIP_UPLOAD_ERROR = "IMAGE_ZIP_UPLOAD_ERROR";
export const IMAGE_DELETE = "IMAGE_DELETE";
export const IMAGE_DELETE_SUCCESS = "IMAGE_DELETE_SUCCESS";
export const IMAGE_DELETE_ERROR = "IMAGE_DELETE_ERROR";

export const POST_FINDALL = "POST_FINDALL";
export const POST_FINDALL_SUCCESS = "POST_FINDALL_SUCCESS";
export const POST_FINDALL_ERROR = "POST_FINDALL_ERROR";
export const POST_DELETE = "POST_DELETE";
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";
export const POST_DELETE_ERROR = "POST_DELETE_ERROR";

/** PARTNER */
export const PARTNER_FINDALL = "PARTNER_FINDALL";
export const PARTNER_FINDALL_SUCCESS = "PARTNER_FINDALL_SUCCESS";
export const PARTNER_FINDALL_ERROR = "PARTNER_FINDALL_ERROR";
export const PARTNER_CREATE = "PARTNER_CREATE";
export const PARTNER_CREATE_SUCCESS = "PARTNER_CREATE_SUCCESS";
export const PARTNER_CREATE_ERROR = "PARTNER_CREATE_ERROR";
export const PARTNER_DELETE = "PARTNER_DELETE";
export const PARTNER_DELETE_SUCCESS = "PARTNER_DELETE_SUCCESS";
export const PARTNER_DELETE_ERROR = "PARTNER_DELETE_ERROR";
/** END PARTNER*/

/* SETTINGS */
export const CHANGE_LOCALE = "CHANGE_LOCALE";

/* AUTH */
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

/* MENU */
export const MENU_SET_CLASSNAMES = "MENU_SET_CLASSNAMES";
export const MENU_CONTAINER_ADD_CLASSNAME = "MENU_CONTAINER_ADD_CLASSNAME";
export const MENU_CLICK_MOBILE_MENU = "MENU_CLICK_MOBILE_MENU";
export const MENU_CHANGE_DEFAULT_CLASSES = "MENU_CHANGE_DEFAULT_CLASSES";
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS =
  "MENU_CHANGE_HAS_SUB_ITEM_STATUS";

/* TODOAPP*/
export const TODO_GET_LIST = "TODO_GET_LIST";
export const TODO_GET_LIST_SUCCESS = "TODO_GET_LIST_SUCCESS";
export const TODO_GET_LIST_ERROR = "TODO_GET_LIST_ERROR";
export const TODO_GET_LIST_WITH_FILTER = "TODO_GET_LIST_WITH_FILTER";
export const TODO_GET_LIST_WITH_ORDER = "TODO_GET_LIST_WITH_ORDER";
export const TODO_GET_LIST_SEARCH = "TODO_GET_LIST_SEARCH";
export const TODO_ADD_ITEM = "TODO_ADD_ITEM";
export const TODO_ADD_ITEM_SUCCESS = "TODO_ADD_ITEM_SUCCESS";
export const TODO_ADD_ITEM_ERROR = "TODO_ADD_ITEM_ERROR";
export const TODO_SELECTED_ITEMS_CHANGE = "TODO_SELECTED_ITEMS_CHANGE";

/* CHAT APP*/
export const CHAT_GET_CONTACTS = "CHAT_GET_CONTACTS";
export const CHAT_GET_CONTACTS_SUCCESS = "CHAT_GET_CONTACTS_SUCCESS";
export const CHAT_GET_CONTACTS_ERROR = "CHAT_GET_CONTACTS_ERROR";
export const CHAT_GET_CONVERSATIONS = "CHAT_GET_CONVERSATIONS";
export const CHAT_GET_CONVERSATIONS_SUCCESS = "CHAT_GET_CONVERSATIONS_SUCCESS";
export const CHAT_GET_CONVERSATIONS_ERROR = "CHAT_GET_CONVERSATIONS_ERROR";
export const CHAT_ADD_MESSAGE_TO_CONVERSATION =
  "CHAT_ADD_MESSAGE_TO_CONVERSATION";
export const CHAT_CREATE_CONVERSATION = "CHAT_CREATE_CONVERSATION";
export const CHAT_SEARCH_CONTACT = "CHAT_SEARCH_CONTACT";
export const CHAT_CHANGE_CONVERSATION = "CHAT_CHANGE_CONVERSATION";

/* SURVEY LIST APP*/
export const SURVEY_LIST_GET_LIST = "SURVEY_LIST_GET_LIST";
export const SURVEY_LIST_GET_LIST_SUCCESS = "SURVEY_LIST_GET_LIST_SUCCESS";
export const SURVEY_LIST_GET_LIST_ERROR = "SURVEY_LIST_GET_LIST_ERROR";
export const SURVEY_LIST_GET_LIST_WITH_FILTER =
  "SURVEY_LIST_GET_LIST_WITH_FILTER";
export const SURVEY_LIST_GET_LIST_WITH_ORDER =
  "SURVEY_LIST_GET_LIST_WITH_ORDER";
export const SURVEY_LIST_GET_LIST_SEARCH = "SURVEY_LIST_GET_LIST_SEARCH";
export const SURVEY_LIST_ADD_ITEM = "SURVEY_LIST_ADD_ITEM";
export const SURVEY_LIST_ADD_ITEM_SUCCESS = "SURVEY_LIST_ADD_ITEM_SUCCESS";
export const SURVEY_LIST_ADD_ITEM_ERROR = "SURVEY_LIST_ADD_ITEM_ERROR";
export const SURVEY_LIST_SELECTED_ITEMS_CHANGE =
  "SURVEY_LIST_SELECTED_ITEMS_CHANGE";

/* SURVEY DETAIL APP*/
export const SURVEY_GET_DETAILS = "SURVEY_GET_DETAILS";
export const SURVEY_GET_DETAILS_SUCCESS = "SURVEY_GET_DETAILS_SUCCESS";
export const SURVEY_GET_DETAILS_ERROR = "SURVEY_GET_DETAILS_ERROR";
export const SURVEY_DELETE_QUESTION = "SURVEY_DELETE_QUESTION";
export const SURVEY_SAVE = "SURVEY_SAVE";




export * from "./menu/actions";
export * from "./settings/actions";
export * from "./auth/actions";
export * from "./todo/actions";
export * from "./chat/actions";
export * from "./surveyList/actions";
export * from "./surveyDetail/actions";
export * from "./category/actions";
export * from "./image/actions";
export * from "./product/actions";
export * from "./order/actions";
export * from "./user/actions"
export * from "./post/actions"
export * from './partner/actions'
